name: Build OpenCV 4.x STATIC Pure Bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_windows_bundle:
    name: Build Pure Static Bundle on Windows
    runs-on: windows-2025

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4

      - name: Clone OpenCV Core
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv
          ref: 4.x
          path: opencv
          fetch-depth: 1

      - name: Clone OpenCV Contrib
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv_contrib
          ref: 4.x
          path: opencv_contrib
          fetch-depth: 1

      # ОНОВЛЕНО: Перемикаємо хмарне оточення на Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy ninja cmake setuptools wheel build scikit-build

      - name: Compile OpenCV via CMake
        shell: powershell
        run: |
          mkdir opencv/build
          cd opencv/build
          
          # GStreamer вимкнено для початкового базового тесту ядра
          cmake -G "Ninja" `
            -D CMAKE_BUILD_TYPE=RELEASE `
            -D WITH_GSTREAMER=OFF `
            -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules `
            -D BUILD_EXAMPLES=OFF `
            -D BUILD_opencv_apps=OFF `
            -D BUILD_SHARED_LIBS=OFF `
            -D BUILD_opencv_world=ON `
            -D BUILD_opencv_python3=ON `
            -D OPENCV_FORCE_PYTHON_LIBS=ON `
            -D PYTHON3_EXECUTABLE="$env:pythonLocation\python.exe" `
            ..
          ninja

      - name: Prepare Pure Portable Bundle
        shell: powershell
        run: |
          mkdir bundle_output/cv2
          
          # Знаходимо чистий статичний pyd-файл
          Get-ChildItem -Path opencv/build -Filter "cv2*.pyd" -Recurse | Copy-Item -Destination bundle_output/cv2/cv2.pyd -Force
          
          # Створюємо базовий __init__.py для імпорту
          \$InitContent = @'
          from .cv2 import *
          '@
          Set-Content -Path bundle_output/cv2/__init__.py -Value \$InitContent

      - name: Upload Pure Portable Bundle
        uses: actions/upload-artifact@v4
        with:
          name: opencv-4.x-PURE-STATIC-bundle-py311
          path: ./bundle_output/cv2/
          if-no-files-found: error
